export interface Product {
  id: string;
  name: string;
  category: string;
  priceTag: string; // e.g. "500g", "1 kg", "1 Bunch"
  image: string;
  mrp: number;
  sp: number;
  discount: string; // e.g. "25% OFF"
}

export const products: Product[] = [
  // Fruits
  {
    id: "green-apple",
    name: "Fresh Organic Crispy Green Apple (Direct from Farm)",
    category: "fruits",
    priceTag: "500g",
    image: "/green-apple.webp",
    mrp: 3.99,
    sp: 2.99,
    discount: "25% OFF",
  },
  {
    id: "organic-banana",
    name: "Premium Quality Cavendish Organic Ripe Banana",
    category: "fruits",
    priceTag: "1kg",
    image: "/organic-banana.webp",
    mrp: 2.50,
    sp: 1.99,
    discount: "20% OFF",
  },
  {
    id: "fresh-orange",
    name: "Sweet Juicy Orange",
    category: "fruits",
    priceTag: "1 Bunch",
    image: "/fresh-orange.webp",
    mrp: 4.00,
    sp: 3.20,
    discount: "20% OFF",
  },
  {
    id: "fresh-strawberry",
    name: "Fresh Farm Sweet Strawberry (Pack)",
    category: "fruits",
    priceTag: "250g",
    image: "/fresh-strawberry.webp",
    mrp: 4.99,
    sp: 3.99,
    discount: "20% OFF",
  },
  {
    id: "green-grapes",
    name: "Sweet Crispy Seedless Green Grapes",
    category: "fruits",
    priceTag: "500g",
    image: "/green-grapes.webp",
    mrp: 3.80,
    sp: 2.85,
    discount: "25% OFF",
  },
  // Vegetables
  {
    id: "red-tomato",
    name: "Fresh Red Tomato",
    category: "vegetables",
    priceTag: "500g",
    image: "/red-tomato.webp",
    mrp: 3.50,
    sp: 2.45,
    discount: "30% OFF",
  },
  {
    id: "organic-carrot",
    name: "Organic Sweet Carrot",
    category: "vegetables",
    priceTag: "500g",
    image: "/hand_carrots.webp",
    mrp: 2.99,
    sp: 2.39,
    discount: "20% OFF",
  },
  {
    id: "fresh-broccoli",
    name: "Organic Broccoli Crown",
    category: "vegetables",
    priceTag: "1 Unit",
    image: "/fresh-broccoli.webp",
    mrp: 4.50,
    sp: 3.60,
    discount: "20% OFF",
  },
  {
    id: "fresh-potato",
    name: "New Season Russet Potatoes",
    category: "vegetables",
    priceTag: "1kg",
    image: "/fresh-potato.webp",
    mrp: 2.80,
    sp: 1.96,
    discount: "30% OFF",
  },
  {
    id: "fresh-spinach",
    name: "Fresh Organic Baby Spinach (Bunch)",
    category: "vegetables",
    priceTag: "1 Bunch",
    image: "/fresh-spinach.webp",
    mrp: 1.99,
    sp: 1.49,
    discount: "25% OFF",
  },
  // Dairy & Eggs
  {
    id: "organic-milk",
    name: "Organic Whole Milk Bottle",
    category: "dairy",
    priceTag: "1L",
    image: "/organic-milk.webp",
    mrp: 3.20,
    sp: 2.80,
    discount: "12% OFF",
  },
  {
    id: "farm-eggs",
    name: "Free Range Grade A Eggs Carton",
    category: "dairy",
    priceTag: "12 Units",
    image: "/farm-eggs.webp",
    mrp: 5.50,
    sp: 4.40,
    discount: "20% OFF",
  },
  {
    id: "cheddar-cheese",
    name: "Aged Sharp Cheddar Cheese Block",
    category: "dairy",
    priceTag: "250g",
    image: "/cheddar-cheese.webp",
    mrp: 4.50,
    sp: 3.60,
    discount: "20% OFF",
  },
  {
    id: "greek-yogurt",
    name: "Creamy Plain Greek Yogurt Tub",
    category: "dairy",
    priceTag: "500g",
    image: "/greek-yogurt.webp",
    mrp: 3.99,
    sp: 3.19,
    discount: "20% OFF",
  },
  // Bakery
  {
    id: "sourdough-bread",
    name: "Artisanal Stoneground Multigrain Sourdough Bread",
    category: "bakery",
    priceTag: "1 Loaf",
    image: "/sourdough-bread.webp",
    mrp: 4.50,
    sp: 3.99,
    discount: "11% OFF",
  },
  {
    id: "butter-croissant",
    name: "Golden Butter Croissant (Family Pack)",
    category: "bakery",
    priceTag: "4 Units",
    image: "/butter-croissant.webp",
    mrp: 6.00,
    sp: 4.80,
    discount: "20% OFF",
  },
  {
    id: "chocolate-cookie",
    name: "Freshly Baked Chocolate Chip Cookies",
    category: "bakery",
    priceTag: "6 Units",
    image: "/chocolate-cookie.webp",
    mrp: 4.50,
    sp: 3.60,
    discount: "20% OFF",
  },
  // Beverages
  {
    id: "orange-juice",
    name: "Cold Pressed 100% Pure Orange Juice",
    category: "beverages",
    priceTag: "1L",
    image: "/orange-juice.webp",
    mrp: 5.00,
    sp: 4.00,
    discount: "20% OFF",
  },
  {
    id: "coconut-water",
    name: "Pure Hydrating Coconut Water",
    category: "beverages",
    priceTag: "330ml",
    image: "/coconut-water.webp",
    mrp: 2.50,
    sp: 2.00,
    discount: "20% OFF",
  },
  {
    id: "green-tea",
    name: "Organic Matcha Green Tea Bags Pack",
    category: "beverages",
    priceTag: "25 Bags",
    image: "/green-tea.webp",
    mrp: 5.50,
    sp: 4.40,
    discount: "20% OFF",
  },
  // Beauty & Care
  {
    id: "organic-shampoo",
    name: "Organic Herbal Tea Tree Shampoo",
    category: "beauty",
    priceTag: "400ml",
    image: "/organic-shampoo.webp",
    mrp: 11.99,
    sp: 8.99,
    discount: "25% OFF",
  },
  {
    id: "aloe-vera-gel",
    name: "Pure Soothing Aloe Vera Gel",
    category: "beauty",
    priceTag: "300g",
    image: "/aloe-vera-gel.webp",
    mrp: 6.99,
    sp: 5.49,
    discount: "21% OFF",
  },
  // Snacks & Sweets
  {
    id: "salted-almonds",
    name: "Roasted Salted California Almonds",
    category: "snacks",
    priceTag: "250g",
    image: "/salted-almonds.webp",
    mrp: 8.99,
    sp: 6.99,
    discount: "22% OFF",
  },
  {
    id: "dark-chocolate",
    name: "Organic 70% Cocoa Dark Chocolate Bar",
    category: "snacks",
    priceTag: "100g",
    image: "/dark-chocolate.webp",
    mrp: 4.50,
    sp: 3.49,
    discount: "22% OFF",
  },
  // Meat & Seafood
  {
    id: "chicken-breast",
    name: "Organic Free Range Chicken Breast",
    category: "meat",
    priceTag: "500g",
    image: "/chicken-breast.webp",
    mrp: 12.99,
    sp: 9.99,
    discount: "23% OFF",
  },
  {
    id: "salmon-fillet",
    name: "Wild Caught Alaskan Salmon Fillet",
    category: "meat",
    priceTag: "300g",
    image: "/salmon-fillet.webp",
    mrp: 18.99,
    sp: 14.99,
    discount: "21% OFF",
  },
  // Pantry & Staples
  {
    id: "olive-oil",
    name: "Extra Virgin Organic Olive Oil",
    category: "pantry",
    priceTag: "500ml",
    image: "/olive-oil.webp",
    mrp: 15.99,
    sp: 12.99,
    discount: "18% OFF",
  },
  {
    id: "basmati-rice",
    name: "Premium Long Grain Basmati Rice",
    category: "pantry",
    priceTag: "1kg",
    image: "/basmati-rice.webp",
    mrp: 9.99,
    sp: 7.49,
    discount: "25% OFF",
  },
  // Frozen Foods
  {
    id: "frozen-berries",
    name: "Organic Frozen Mixed Berries Triple Pack",
    category: "frozen",
    priceTag: "400g",
    image: "/frozen-berries.webp",
    mrp: 7.99,
    sp: 6.49,
    discount: "18% OFF",
  },
  {
    id: "frozen-pizza",
    name: "Stone Baked Organic Vegetable Pizza",
    category: "frozen",
    priceTag: "1 Unit",
    image: "/frozen-pizza.webp",
    mrp: 10.99,
    sp: 8.99,
    discount: "18% OFF",
  },
  // Household & Cleaning
  {
    id: "dish-soap",
    name: "Plant-Based Lavender Dish Soap",
    category: "household",
    priceTag: "500ml",
    image: "/dish-soap.webp",
    mrp: 4.99,
    sp: 3.99,
    discount: "20% OFF",
  },
  {
    id: "laundry-detergent",
    name: "Eco-Friendly Liquid Laundry Detergent",
    category: "household",
    priceTag: "1.5L",
    image: "/laundry-detergent.webp",
    mrp: 14.99,
    sp: 11.99,
    discount: "20% OFF",
  },
  // Baby Care
  {
    id: "baby-wipes",
    name: "Sensitive Skin Organic Baby Wipes",
    category: "baby",
    priceTag: "80 Pack",
    image: "/baby-wipes.webp",
    mrp: 5.99,
    sp: 4.49,
    discount: "25% OFF",
  },
  {
    id: "baby-puree",
    name: "Organic Pear & Spinach Baby Puree Pack",
    category: "baby",
    priceTag: "120g",
    image: "/baby-puree.webp",
    mrp: 2.99,
    sp: 2.29,
    discount: "23% OFF",
  },
  // Pet Supplies
  {
    id: "dog-food",
    name: "Grain-Free Salmon & Sweet Potato Dog Food",
    category: "pets",
    priceTag: "2kg",
    image: "/dog-food.webp",
    mrp: 23.99,
    sp: 18.99,
    discount: "20% OFF",
  },
  {
    id: "cat-treats",
    name: "Natural Freeze-Dried Chicken Cat Treats",
    category: "pets",
    priceTag: "100g",
    image: "/cat-treats.webp",
    mrp: 7.49,
    sp: 5.99,
    discount: "20% OFF",
  },
  // Organic & Health
  {
    id: "raw-honey",
    name: "Unfiltered Organic Raw Honey Jar",
    category: "organic",
    priceTag: "400g",
    image: "/raw-honey.webp",
    mrp: 10.99,
    sp: 8.49,
    discount: "22% OFF",
  },
  {
    id: "chia-seeds",
    name: "Premium Organic Chia Seeds",
    category: "organic",
    priceTag: "300g",
    image: "/chia-seeds.webp",
    mrp: 5.99,
    sp: 4.99,
    discount: "16% OFF",
  },
  // Pharmacy & Wellness
  {
    id: "vitamin-c",
    name: "Organic Vitamin C Gummies 90ct",
    category: "pharmacy",
    priceTag: "90 Units",
    image: "/vitamin-c.webp",
    mrp: 13.99,
    sp: 10.99,
    discount: "21% OFF",
  },
  {
    id: "throat-lozenges",
    name: "Honey Lemon Herbal Throat Lozenges",
    category: "pharmacy",
    priceTag: "20 Units",
    image: "/throat-lozenges.webp",
    mrp: 4.99,
    sp: 3.99,
    discount: "20% OFF",
  },
  // Kitchen & Home
  {
    id: "bamboo-cutting-board",
    name: "Premium Organic Bamboo Cutting Board",
    category: "kitchen",
    priceTag: "1 Unit",
    image: "/bamboo-cutting-board.webp",
    mrp: 19.99,
    sp: 15.99,
    discount: "20% OFF",
  },
  {
    id: "reusable-wraps",
    name: "Organic Beeswax Reusable Food Wraps (3-Pack)",
    category: "kitchen",
    priceTag: "3 Pack",
    image: "/reusable-wraps.webp",
    mrp: 14.99,
    sp: 12.49,
    discount: "16% OFF",
  },
  // Gifts & Flowers
  {
    id: "roses-bouquet",
    name: "Fresh Red Roses Bouquet (12 Stems)",
    category: "gifts",
    priceTag: "12 Stems",
    image: "/roses-bouquet.webp",
    mrp: 29.99,
    sp: 24.99,
    discount: "16% OFF",
  },
  {
    id: "gift-basket",
    name: "Organic Gourmet Fruits Gift Basket",
    category: "gifts",
    priceTag: "1 Unit",
    image: "/gift-basket.webp",
    mrp: 39.99,
    sp: 34.99,
    discount: "12% OFF",
  },
];
