export interface Product {
  id: string;
  name: string;
  category: string;
  priceTag: string; // e.g. "500g", "1 kg", "1 Bunch"
  image: string;
  mrp: number;
  sp: number;
  discount: string; // e.g. "25% OFF"
}

export const products: Product[] = [
  // Fruits
  {
    id: "green-apple",
    name: "Fresh Organic Crispy Green Apple (Direct from Farm)",
    category: "fruits",
    priceTag: "500g",
    image: "/green-apple.webp",
    mrp: 3.99,
    sp: 2.99,
    discount: "25% OFF",
  },
  {
    id: "organic-banana",
    name: "Premium Quality Cavendish Organic Ripe Banana",
    category: "fruits",
    priceTag: "1kg",
    image: "/organic-banana.webp",
    mrp: 2.50,
    sp: 1.99,
    discount: "20% OFF",
  },
  {
    id: "fresh-orange",
    name: "Sweet Juicy Orange",
    category: "fruits",
    priceTag: "1 Bunch",
    image: "/fresh-orange.webp",
    mrp: 4.00,
    sp: 3.20,
    discount: "20% OFF",
  },
  {
    id: "fresh-strawberry",
    name: "Fresh Farm Sweet Strawberry (Pack)",
    category: "fruits",
    priceTag: "250g",
    image: "/fresh-strawberry.webp",
    mrp: 4.99,
    sp: 3.99,
    discount: "20% OFF",
  },
  {
    id: "green-grapes",
    name: "Sweet Crispy Seedless Green Grapes",
    category: "fruits",
    priceTag: "500g",
    image: "/green-grapes.webp",
    mrp: 3.80,
    sp: 2.85,
    discount: "25% OFF",
  },
  // Vegetables
  {
    id: "red-tomato",
    name: "Fresh Red Tomato",
    category: "vegetables",
    priceTag: "500g",
    image: "/red-tomato.webp",
    mrp: 3.50,
    sp: 2.45,
    discount: "30% OFF",
  },
  {
    id: "organic-carrot",
    name: "Organic Sweet Carrot",
    category: "vegetables",
    priceTag: "500g",
    image: "/hand_carrots.webp",
    mrp: 2.99,
    sp: 2.39,
    discount: "20% OFF",
  },
  {
    id: "fresh-broccoli",
    name: "Organic Broccoli Crown",
    category: "vegetables",
    priceTag: "1 Unit",
    image: "/fresh-broccoli.webp",
    mrp: 4.50,
    sp: 3.60,
    discount: "20% OFF",
  },
  {
    id: "fresh-potato",
    name: "New Season Russet Potatoes",
    category: "vegetables",
    priceTag: "1kg",
    image: "/fresh-potato.webp",
    mrp: 2.80,
    sp: 1.96,
    discount: "30% OFF",
  },
  {
    id: "fresh-spinach",
    name: "Fresh Organic Baby Spinach (Bunch)",
    category: "vegetables",
    priceTag: "1 Bunch",
    image: "/fresh-spinach.webp",
    mrp: 1.99,
    sp: 1.49,
    discount: "25% OFF",
  },
  // Dairy & Eggs
  {
    id: "organic-milk",
    name: "Organic Whole Milk Bottle",
    category: "dairy",
    priceTag: "1L",
    image: "/organic-milk.webp",
    mrp: 3.20,
    sp: 2.80,
    discount: "12% OFF",
  },
  {
    id: "farm-eggs",
    name: "Free Range Grade A Eggs Carton",
    category: "dairy",
    priceTag: "12 Units",
    image: "/farm-eggs.webp",
    mrp: 5.50,
    sp: 4.40,
    discount: "20% OFF",
  },
  {
    id: "cheddar-cheese",
    name: "Aged Sharp Cheddar Cheese Block",
    category: "dairy",
    priceTag: "250g",
    image: "/cheddar-cheese.webp",
    mrp: 4.50,
    sp: 3.60,
    discount: "20% OFF",
  },
  {
    id: "greek-yogurt",
    name: "Creamy Plain Greek Yogurt Tub",
    category: "dairy",
    priceTag: "500g",
    image: "/greek-yogurt.webp",
    mrp: 3.99,
    sp: 3.19,
    discount: "20% OFF",
  },
  // Bakery
  {
    id: "sourdough-bread",
    name: "Artisanal Stoneground Multigrain Sourdough Bread",
    category: "bakery",
    priceTag: "1 Loaf",
    image: "/sourdough-bread.webp",
    mrp: 4.50,
    sp: 3.99,
    discount: "11% OFF",
  },
  {
    id: "butter-croissant",
    name: "Golden Butter Croissant (Family Pack)",
    category: "bakery",
    priceTag: "4 Units",
    image: "/butter-croissant.webp",
    mrp: 6.00,
    sp: 4.80,
    discount: "20% OFF",
  },
  {
    id: "chocolate-cookie",
    name: "Freshly Baked Chocolate Chip Cookies",
    category: "bakery",
    priceTag: "6 Units",
    image: "/chocolate-cookie.webp",
    mrp: 4.50,
    sp: 3.60,
    discount: "20% OFF",
  },
  // Beverages
  {
    id: "orange-juice",
    name: "Cold Pressed 100% Pure Orange Juice",
    category: "beverages",
    priceTag: "1L",
    image: "/orange-juice.webp",
    mrp: 5.00,
    sp: 4.00,
    discount: "20% OFF",
  },
  {
    id: "coconut-water",
    name: "Pure Hydrating Coconut Water",
    category: "beverages",
    priceTag: "330ml",
    image: "/coconut-water.webp",
    mrp: 2.50,
    sp: 2.00,
    discount: "20% OFF",
  },
  {
    id: "green-tea",
    name: "Organic Matcha Green Tea Bags Pack",
    category: "beverages",
    priceTag: "25 Bags",
    image: "/green-tea.webp",
    mrp: 5.50,
    sp: 4.40,
    discount: "20% OFF",
  },
];
